name: Build Desktop Downloaders

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        # We build from the subfolder that holds your script + library
        working-directory: BluetoothDownloader

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Pick the correct --add-data separator for the OS
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: >
          pyinstaller
          --onefile
          --name Downloader
          --add-data "library;library"
          --hidden-import serial
          --hidden-import serial.tools.list_ports
          Downloader.py

      - name: Build (macOS/Linux)
        if: runner.os != 'Windows'
        run: >
          pyinstaller
          --onefile
          --name Downloader
          --add-data "library:library"
          --hidden-import serial
          --hidden-import serial.tools.list_ports
          Downloader.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Downloader-${{ runner.os }}
          path: |
            BluetoothDownloader/dist/**
